---
# Ansible Inventory f√ºr Homelab Cluster
# Master-Node: homelab (amd64)
# Worker-Nodes: Raspberry Pis (ARM64)

all:
  children:
    k8s_masters:
      hosts:
        homelab:
          ansible_host: 192.168.178.54
          ansible_user: bernd
          ansible_ssh_private_key_file: ~/.ssh/infra_ed25519
      vars:
        kubernetes_role: master
    
    k8s_workers:
      hosts:
        k8s-worker-8gb:
          ansible_host: 192.168.178.91
          ansible_user: bernd
          ansible_ssh_private_key_file: ~/.ssh/ansible_pi_key
        k8s-worker-15gb:
          ansible_host: 192.168.178.95
          ansible_user: bernd
          ansible_ssh_private_key_file: ~/.ssh/ansible_pi_key
        k8s-worker-4gb:
          ansible_host: 192.168.178.90
          ansible_user: bernd
          ansible_ssh_private_key_file: ~/.ssh/ansible_pi_key
        k8s-worker-1gb:
          ansible_host: 192.168.178.92
          ansible_user: bernd
          ansible_ssh_private_key_file: ~/.ssh/ansible_pi_key
      vars:
        kubernetes_role: worker

