---
# Host-spezifische Variablen f√ºr homelab (Master-Node)

ansible_host: 192.168.178.54
ansible_user: bernd
ansible_ssh_private_key_file: ~/.ssh/infra_ed25519

# Architektur
architecture: amd64

# Storage
storage_ssd_device: "/dev/sda"
storage_ssd_mount_point: "/mnt/k8s-db"

